<template>
    <div class="appSpotContainer">
        <!--<div class="appSpot">-->
            <!--<router-link class="item images" title="ImagesApp" to="/images/gallery"></router-link>-->
        <!--</div>-->
        <!--<div class="appSpot">-->
            <!--<router-link class="item youtube" title="YoutubeApp" to="/youtube"></router-link>-->
        <!--</div>-->
        <div class="appSpot heartbeat">
            <router-link class="item math" title="MatheApp" to="/math">Math</router-link>
        </div>
    </div>
</template>

<script>
  export default {
      name: 'AppSelector',
      methods: {

        }
    };
</script>

<style scoped>

    .appSpotContainer{
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .appSpot{
        border-radius: 50%;
        width:20vw;
        height: 20vw;
        min-width: 85px;
        min-height: 85px;
        display: flex;
        background-color: #9fa6ff;
        align-items: center;
        justify-content: center;
        margin: 20px;
        transition: background-color 100ms linear;
        border: solid 2px #848be4;
        vertical-align:middle;
    }

    .item.math{
        text-align: center;
        text-decoration: none;
        color: black;
        display: block;
        line-height: 85px;
        width:100%;
    }

    .item.math::hover{
    }

    @media screen and (min-width: 480px) {
        .appSpot {
            width:100px;
            height: 100px
        }

        a{
            line-height: 100px;
        }
    }


    .youtube{
        background: url(http://www.slatecube.com/images/play-btn.png);
        width:100%;
        height: 100%;
        background-size: 50px 50px;
        background-repeat: no-repeat;
        background-position: center;
    }

    .images{
        background: url(https://cdn2.iconfinder.com/data/icons/picol-vector/32/image-512.png);
        width:100%;
        height: 100%;
        background-size: 50px 50px;
        background-repeat: no-repeat;
        background-position: center;
    }

    .math{
        font-size: xx-large;
        width:100%;
        height: 100%;
        background-size: 50px 50px;
        background-repeat: no-repeat;
        background-position: center;
    }

    .appSpot:hover{
    }


    .heartbeat {
        -webkit-animation: heartbeat 1.5s ease-in-out 2 both;
        animation: heartbeat 1.5s ease-in-out 2 both;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2019-2-4 14:54:37
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation heartbeat
     * ----------------------------------------
     */
    @-webkit-keyframes heartbeat {
        from {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-transform-origin: center center;
            transform-origin: center center;
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        10% {
            -webkit-transform: scale(0.91);
            transform: scale(0.91);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        17% {
            -webkit-transform: scale(0.98);
            transform: scale(0.98);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        33% {
            -webkit-transform: scale(0.87);
            transform: scale(0.87);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        45% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
    }
    @keyframes heartbeat {
        from {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-transform-origin: center center;
            transform-origin: center center;
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        10% {
            -webkit-transform: scale(0.91);
            transform: scale(0.91);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        17% {
            -webkit-transform: scale(0.98);
            transform: scale(0.98);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        33% {
            -webkit-transform: scale(0.87);
            transform: scale(0.87);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        45% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
    }


</style>